# Generated by Django 4.2.4 on 2023-09-02 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_nome_produto_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='item',
            new_name='nome_do_item',
        ),
    ]
